export interface DetailedExerciseModel {
    Workout?: string,
    id: number,
    workoutId: number,
    Workout_Day?: string,
    exerciseId: number,
    reps: number | string,
    sets: number,
    tempo?: string,
    rests: number | string,
    supersetId?: string,
}

export const DetailedExerciseDb:Array<DetailedExerciseModel> = [
  {
    Workout: "Chisel",
    id: 63,
    workoutId: 7,
    Workout_Day: "Arms",
    exerciseId: 2080,
    reps: 12,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 62,
    workoutId: 7,
    Workout_Day: "Arms",
    exerciseId: 340,
    reps: 12,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 61,
    workoutId: 7,
    Workout_Day: "Arms",
    exerciseId: 167,
    reps: "10-15",
    sets: 2,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 60,
    workoutId: 7,
    Workout_Day: "Arms",
    exerciseId: 167,
    reps: 12,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 59,
    workoutId: 6,
    Workout_Day: "Chest",
    exerciseId: 2100,
    reps: 100,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 58,
    workoutId: 6,
    Workout_Day: "Chest",
    exerciseId: 188,
    reps: "8-10",
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 57,
    workoutId: 6,
    Workout_Day: "Chest",
    exerciseId: 507,
    reps: "8-10",
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 56,
    workoutId: 6,
    Workout_Day: "Chest",
    exerciseId: 455,
    reps: "8-10",
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 55,
    workoutId: 6,
    Workout_Day: "Chest",
    exerciseId: 1766,
    reps: 12,
    sets: 4,
    tempo: "",
    rests: 30,
  },
  {
    Workout: "Chisel",
    id: 54,
    workoutId: 6,
    Workout_Day: "Chest",
    exerciseId: 325,
    reps: 12,
    sets: 4,
    tempo: "",
    rests: 30,
  },
  {
    Workout: "Chisel",
    id: 53,
    workoutId: 6,
    Workout_Day: "Chest",
    exerciseId: 2100,
    reps: "to failure",
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 52,
    workoutId: 5,
    Workout_Day: "Legs, Cardio, Abs",
    exerciseId: 1739,
    reps: "5-10",
    sets: 2,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 51,
    workoutId: 5,
    Workout_Day: "Legs, Cardio, Abs",
    exerciseId: 1739,
    reps: 12,
    sets: 3,
    tempo: "",
    rests: 45,
  },
  {
    Workout: "Chisel",
    id: 50,
    workoutId: 5,
    Workout_Day: "Legs, Cardio, Abs",
    exerciseId: 2232,
    reps: 12,
    sets: 3,
    tempo: "",
    rests: 45,
  },
  {
    Workout: "Chisel",
    id: 49,
    workoutId: 5,
    Workout_Day: "Legs, Cardio, Abs",
    exerciseId: 159,
    reps: "10, 8, 6, 5",
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 48,
    workoutId: 5,
    Workout_Day: "Legs, Cardio, Abs",
    exerciseId: 160,
    reps: 10,
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 47,
    workoutId: 5,
    Workout_Day: "Legs, Cardio, Abs",
    exerciseId: 178,
    reps: 12,
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 46,
    workoutId: 5,
    Workout_Day: "Legs, Cardio, Abs",
    exerciseId: 210,
    reps: 10,
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 45,
    workoutId: 5,
    Workout_Day: "Legs, Cardio, Abs",
    exerciseId: 2715,
    reps: "40 sec",
    sets: 15,
    tempo: "",
    rests: 40,
  },
  {
    Workout: "Chisel",
    id: 44,
    workoutId: 5,
    Workout_Day: "Legs, Cardio, Abs",
    exerciseId: 4,
    reps: 15,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 43,
    workoutId: 5,
    Workout_Day: "Legs, Cardio, Abs",
    exerciseId: 367,
    reps: 10,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 42,
    workoutId: 5,
    Workout_Day: "Legs, Cardio, Abs",
    exerciseId: 5,
    reps: 10,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 41,
    workoutId: 4,
    Workout_Day: "Cardio, Abs, Shoulders",
    exerciseId: 2714,
    reps: "60 mins",
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 40,
    workoutId: 4,
    Workout_Day: "Cardio, Abs, Shoulders",
    exerciseId: 458,
    reps: 20,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 39,
    workoutId: 4,
    Workout_Day: "Cardio, Abs, Shoulders",
    exerciseId: 913,
    reps: "to failure",
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 38,
    workoutId: 4,
    Workout_Day: "Cardio, Abs, Shoulders",
    exerciseId: 471,
    reps: 20,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 37,
    workoutId: 4,
    Workout_Day: "Cardio, Abs, Shoulders",
    exerciseId: 902,
    reps: 20,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 36,
    workoutId: 4,
    Workout_Day: "Cardio, Abs, Shoulders",
    exerciseId: 1929,
    reps: 12,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 35,
    workoutId: 4,
    Workout_Day: "Cardio, Abs, Shoulders",
    exerciseId: 2513,
    reps: "6, 8, 8",
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 34,
    workoutId: 4,
    Workout_Day: "Cardio, Abs, Shoulders",
    exerciseId: 2354,
    reps: "6, 8, 8",
    sets: 3,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 33,
    workoutId: 4,
    Workout_Day: "Cardio, Abs, Shoulders",
    exerciseId: 570,
    reps: "15-20",
    sets: 3,
    tempo: "",
    rests: 20,
  },
  {
    Workout: "Chisel",
    id: 32,
    workoutId: 4,
    Workout_Day: "Cardio, Abs, Shoulders",
    exerciseId: 2245,
    reps: 15,
    sets: 3,
    tempo: "",
    rests: 20,
  },
  {
    Workout: "Chisel",
    id: 31,
    workoutId: 4,
    Workout_Day: "Cardio, Abs, Shoulders",
    exerciseId: 214,
    reps: "1 mins",
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 30,
    workoutId: 3,
    Workout_Day: "Back, Cardio, Abs",
    exerciseId: 2085,
    reps: 50,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 29,
    workoutId: 3,
    Workout_Day: "Back, Cardio, Abs",
    exerciseId: 2888,
    reps: "6, 8, 8",
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 28,
    workoutId: 3,
    Workout_Day: "Back, Cardio, Abs",
    exerciseId: 249,
    reps: "6, 8, 8",
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 27,
    workoutId: 3,
    Workout_Day: "Back, Cardio, Abs",
    exerciseId: 1723,
    reps: "6, 8, 8",
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 26,
    workoutId: 3,
    Workout_Day: "Back, Cardio, Abs",
    exerciseId: 347,
    reps: "6, 8, 8",
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 25,
    workoutId: 3,
    Workout_Day: "Back, Cardio, Abs",
    exerciseId: 354,
    reps: 15,
    sets: 3,
    tempo: "",
    rests: 45,
  },
  {
    Workout: "Chisel",
    id: 24,
    workoutId: 3,
    Workout_Day: "Back, Cardio, Abs",
    exerciseId: 412,
    reps: 15,
    sets: 3,
    tempo: "",
    rests: 45,
  },
  {
    Workout: "Chisel",
    id: 23,
    workoutId: 3,
    Workout_Day: "Back, Cardio, Abs",
    exerciseId: 2715,
    reps: "40 sec",
    sets: 15,
    tempo: "",
    rests: 40,
  },
  {
    Workout: "Chisel",
    id: 22,
    workoutId: 3,
    Workout_Day: "Back, Cardio, Abs",
    exerciseId: 4,
    reps: 15,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 21,
    workoutId: 3,
    Workout_Day: "Back, Cardio, Abs",
    exerciseId: 367,
    reps: 10,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 20,
    workoutId: 3,
    Workout_Day: "Back, Cardio, Abs",
    exerciseId: 5,
    reps: 10,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 19,
    workoutId: 2,
    Workout_Day: "Abs, Cardio, Arms",
    exerciseId: 2714,
    reps: "60 mins",
    sets: 1,
    tempo: "",
    rests: "",
  },
  {
    Workout: "Chisel",
    id: 18,
    workoutId: 2,
    Workout_Day: "Abs, Cardio, Arms",
    exerciseId: 458,
    reps: 20,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 17,
    workoutId: 2,
    Workout_Day: "Abs, Cardio, Arms",
    exerciseId: 913,
    reps: "to failure",
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 16,
    workoutId: 2,
    Workout_Day: "Abs, Cardio, Arms",
    exerciseId: 471,
    reps: 20,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 15,
    workoutId: 2,
    Workout_Day: "Abs, Cardio, Arms",
    exerciseId: 167,
    reps: "10-15",
    sets: 2,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 14,
    workoutId: 2,
    Workout_Day: "Abs, Cardio, Arms",
    exerciseId: 167,
    reps: 12,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 13,
    workoutId: 2,
    Workout_Day: "Abs, Cardio, Arms",
    exerciseId: 2080,
    reps: 12,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 12,
    workoutId: 2,
    Workout_Day: "Abs, Cardio, Arms",
    exerciseId: 340,
    reps: 12,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 11,
    workoutId: 1,
    Workout_Day: "Chest, Cardio, Abs",
    exerciseId: 2100,
    reps: 100,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 10,
    workoutId: 1,
    Workout_Day: "Chest, Cardio, Abs",
    exerciseId: 188,
    reps: "8-10",
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 9,
    workoutId: 1,
    Workout_Day: "Chest, Cardio, Abs",
    exerciseId: 507,
    reps: "8-10",
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 8,
    workoutId: 1,
    Workout_Day: "Chest, Cardio, Abs",
    exerciseId: 455,
    reps: "8-10",
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 7,
    workoutId: 1,
    Workout_Day: "Chest, Cardio, Abs",
    exerciseId: 1766,
    reps: 12,
    sets: 4,
    tempo: "",
    rests: 30,
  },
  {
    Workout: "Chisel",
    id: 6,
    workoutId: 1,
    Workout_Day: "Chest, Cardio, Abs",
    exerciseId: 325,
    reps: 12,
    sets: 4,
    tempo: "",
    rests: 30,
  },
  {
    Workout: "Chisel",
    id: 5,
    workoutId: 1,
    Workout_Day: "Chest, Cardio, Abs",
    exerciseId: 2100,
    reps: "to failure",
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "Chisel",
    id: 4,
    workoutId: 1,
    Workout_Day: "Chest, Cardio, Abs",
    exerciseId: 2715,
    reps: "40 sec",
    sets: 15,
    tempo: "",
    rests: 40,
  },
  {
    Workout: "Chisel",
    id: 3,
    workoutId: 1,
    Workout_Day: "Chest, Cardio, Abs",
    exerciseId: 4,
    reps: 15,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 2,
    workoutId: 1,
    Workout_Day: "Chest, Cardio, Abs",
    exerciseId: 367,
    reps: 10,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "Chisel",
    id: 1,
    workoutId: 1,
    Workout_Day: "Chest, Cardio, Abs",
    exerciseId: 5,
    reps: 10,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 1",
    id: 64,
    workoutId: 8,
    Workout_Day: "Chest, Back",
    exerciseId: 255,
    reps: 6,
    sets: 6,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 1",
    id: 65,
    workoutId: 8,
    Workout_Day: "Chest, Back",
    exerciseId: 2085,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 66,
    workoutId: 8,
    Workout_Day: "Chest, Back",
    exerciseId: 1569,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 67,
    workoutId: 8,
    Workout_Day: "Chest, Back",
    exerciseId: 2085,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 68,
    workoutId: 8,
    Workout_Day: "Chest, Back",
    exerciseId: 2085,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 69,
    workoutId: 9,
    Workout_Day: "Legs, Abs",
    exerciseId: 5,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 70,
    workoutId: 9,
    Workout_Day: "Legs, Abs",
    exerciseId: 175,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 71,
    workoutId: 9,
    Workout_Day: "Legs, Abs",
    exerciseId: 210,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 72,
    workoutId: 9,
    Workout_Day: "Legs, Abs",
    exerciseId: 159,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 73,
    workoutId: 9,
    Workout_Day: "Legs, Abs",
    exerciseId: 159,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 74,
    workoutId: 10,
    Workout_Day: "Arms",
    exerciseId: 668,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 75,
    workoutId: 10,
    Workout_Day: "Arms",
    exerciseId: 44,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: "",
  },
  {
    Workout: "SWOLE pt 1",
    id: 76,
    workoutId: 10,
    Workout_Day: "Arms",
    exerciseId: 167,
    reps: 6,
    sets: 6,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 77,
    workoutId: 10,
    Workout_Day: "Arms",
    exerciseId: 167,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 78,
    workoutId: 11,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 5,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 79,
    workoutId: 11,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 570,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 80,
    workoutId: 11,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 1929,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 1",
    id: 81,
    workoutId: 11,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 1929,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 2",
    id: 82,
    workoutId: 12,
    Workout_Day: "Chest, Back",
    exerciseId: 551,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 2",
    id: 83,
    workoutId: 12,
    Workout_Day: "Chest, Back",
    exerciseId: 1723,
    reps: 3,
    sets: 3,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 2",
    id: 84,
    workoutId: 12,
    Workout_Day: "Chest, Back",
    exerciseId: 2900,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 2",
    id: 85,
    workoutId: 12,
    Workout_Day: "Chest, Back",
    exerciseId: 347,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 2",
    id: 86,
    workoutId: 12,
    Workout_Day: "Chest, Back",
    exerciseId: 1561,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 2",
    id: 87,
    workoutId: 12,
    Workout_Day: "Chest, Back",
    exerciseId: 388,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 2",
    id: 88,
    workoutId: 12,
    Workout_Day: "Chest, Back",
    exerciseId: 388,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 2",
    id: 89,
    workoutId: 13,
    Workout_Day: "Legs",
    exerciseId: 2511,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 2",
    id: 90,
    workoutId: 13,
    Workout_Day: "Legs",
    exerciseId: 2232,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 2",
    id: 91,
    workoutId: 13,
    Workout_Day: "Legs",
    exerciseId: 1739,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 2",
    id: 92,
    workoutId: 13,
    Workout_Day: "Legs",
    exerciseId: 1743,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 2",
    id: 93,
    workoutId: 13,
    Workout_Day: "Legs",
    exerciseId: 159,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 2",
    id: 94,
    workoutId: 13,
    Workout_Day: "Legs",
    exerciseId: 159,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 2",
    id: 95,
    workoutId: 14,
    Workout_Day: "Arms",
    exerciseId: 354,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 2",
    id: 96,
    workoutId: 14,
    Workout_Day: "Arms",
    exerciseId: 668,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 2",
    id: 97,
    workoutId: 14,
    Workout_Day: "Arms",
    exerciseId: 354,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 2",
    id: 98,
    workoutId: 14,
    Workout_Day: "Arms",
    exerciseId: 404,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 2",
    id: 99,
    workoutId: 14,
    Workout_Day: "Arms",
    exerciseId: 580,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 2",
    id: 100,
    workoutId: 15,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 5,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 2",
    id: 101,
    workoutId: 15,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 198,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 2",
    id: 102,
    workoutId: 15,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 36,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: "",
  },
  {
    Workout: "SWOLE pt 2",
    id: 103,
    workoutId: 15,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 570,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 2",
    id: 104,
    workoutId: 15,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 2216,
    reps: 3,
    sets: 3,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 2",
    id: 105,
    workoutId: 15,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 1929,
    reps: 3,
    sets: 3,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 2",
    id: 106,
    workoutId: 15,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 1929,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 3",
    id: 107,
    workoutId: 16,
    Workout_Day: "Chest, Back",
    exerciseId: 1723,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 3",
    id: 108,
    workoutId: 16,
    Workout_Day: "Chest, Back",
    exerciseId: 2085,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 3",
    id: 109,
    workoutId: 16,
    Workout_Day: "Chest, Back",
    exerciseId: 2900,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 3",
    id: 110,
    workoutId: 16,
    Workout_Day: "Chest, Back",
    exerciseId: 507,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 3",
    id: 111,
    workoutId: 17,
    Workout_Day: "Legs",
    exerciseId: 213,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 3",
    id: 112,
    workoutId: 17,
    Workout_Day: "Legs",
    exerciseId: 210,
    reps: 3,
    sets: 3,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 3",
    id: 113,
    workoutId: 17,
    Workout_Day: "Legs",
    exerciseId: 159,
    reps: 3,
    sets: 3,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 3",
    id: 114,
    workoutId: 18,
    Workout_Day: "Arms",
    exerciseId: 661,
    reps: 3,
    sets: 3,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 3",
    id: 115,
    workoutId: 18,
    Workout_Day: "Arms",
    exerciseId: 2080,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 3",
    id: 116,
    workoutId: 19,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 5,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 3",
    id: 117,
    workoutId: 19,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 198,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 3",
    id: 118,
    workoutId: 19,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 2541,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 3",
    id: 119,
    workoutId: 19,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 93,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 3",
    id: 120,
    workoutId: 20,
    Workout_Day: "Cardio",
    exerciseId: 2716,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 3",
    id: 121,
    workoutId: 20,
    Workout_Day: "Cardio",
    exerciseId: 2715,
    reps: 10,
    sets: 10,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 3",
    id: 122,
    workoutId: 20,
    Workout_Day: "Cardio",
    exerciseId: 2716,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 123,
    workoutId: 21,
    Workout_Day: "Chest, Back",
    exerciseId: 1700,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 124,
    workoutId: 21,
    Workout_Day: "Chest, Back",
    exerciseId: 551,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 125,
    workoutId: 21,
    Workout_Day: "Chest, Back",
    exerciseId: 388,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 126,
    workoutId: 21,
    Workout_Day: "Chest, Back",
    exerciseId: 2085,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 127,
    workoutId: 21,
    Workout_Day: "Chest, Back",
    exerciseId: 2085,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 128,
    workoutId: 22,
    Workout_Day: "Arms",
    exerciseId: 1700,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 129,
    workoutId: 22,
    Workout_Day: "Arms",
    exerciseId: 2080,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 130,
    workoutId: 22,
    Workout_Day: "Arms",
    exerciseId: 44,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: "",
  },
  {
    Workout: "SWOLE pt 4",
    id: 131,
    workoutId: 22,
    Workout_Day: "Arms",
    exerciseId: 167,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 132,
    workoutId: 22,
    Workout_Day: "Arms",
    exerciseId: 167,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 133,
    workoutId: 23,
    Workout_Day: "Legs",
    exerciseId: 1700,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 134,
    workoutId: 23,
    Workout_Day: "Legs",
    exerciseId: 2530,
    reps: 3,
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 4",
    id: 135,
    workoutId: 23,
    Workout_Day: "Legs",
    exerciseId: 2205,
    reps: 3,
    sets: 3,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 4",
    id: 136,
    workoutId: 23,
    Workout_Day: "Legs",
    exerciseId: 2232,
    reps: 10,
    sets: 10,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 4",
    id: 137,
    workoutId: 23,
    Workout_Day: "Legs",
    exerciseId: 1739,
    reps: 10,
    sets: 10,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 4",
    id: 138,
    workoutId: 23,
    Workout_Day: "Legs",
    exerciseId: 159,
    reps: 12,
    sets: 12,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 4",
    id: 139,
    workoutId: 23,
    Workout_Day: "Legs",
    exerciseId: 159,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 4",
    id: 140,
    workoutId: 24,
    Workout_Day: "Chest, Back",
    exerciseId: 1700,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 141,
    workoutId: 24,
    Workout_Day: "Chest, Back",
    exerciseId: 2594,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 142,
    workoutId: 24,
    Workout_Day: "Chest, Back",
    exerciseId: 1561,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 143,
    workoutId: 24,
    Workout_Day: "Chest, Back",
    exerciseId: 163,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 144,
    workoutId: 24,
    Workout_Day: "Chest, Back",
    exerciseId: 163,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 145,
    workoutId: 25,
    Workout_Day: "Arms",
    exerciseId: 1700,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 146,
    workoutId: 25,
    Workout_Day: "Arms",
    exerciseId: 354,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 147,
    workoutId: 26,
    Workout_Day: "Legs",
    exerciseId: 1700,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 148,
    workoutId: 26,
    Workout_Day: "Legs",
    exerciseId: 2205,
    reps: 3,
    sets: 3,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 149,
    workoutId: 26,
    Workout_Day: "Legs",
    exerciseId: 1739,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 150,
    workoutId: 26,
    Workout_Day: "Legs",
    exerciseId: 159,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 4",
    id: 151,
    workoutId: 26,
    Workout_Day: "Legs",
    exerciseId: 159,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 152,
    workoutId: 27,
    Workout_Day: "Chest, Triceps, Abs",
    exerciseId: 194,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 153,
    workoutId: 27,
    Workout_Day: "Chest, Triceps, Abs",
    exerciseId: 668,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 90,
  },
  {
    Workout: "SWOLE pt 5",
    id: 154,
    workoutId: 27,
    Workout_Day: "Chest, Triceps, Abs",
    exerciseId: 1587,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 90,
  },
  {
    Workout: "SWOLE pt 5",
    id: 155,
    workoutId: 27,
    Workout_Day: "Chest, Triceps, Abs",
    exerciseId: 2092,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 156,
    workoutId: 27,
    Workout_Day: "Chest, Triceps, Abs",
    exerciseId: 551,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 157,
    workoutId: 27,
    Workout_Day: "Chest, Triceps, Abs",
    exerciseId: 551,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 5",
    id: 158,
    workoutId: 27,
    Workout_Day: "Chest, Triceps, Abs",
    exerciseId: 163,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 159,
    workoutId: 27,
    Workout_Day: "Chest, Triceps, Abs",
    exerciseId: 163,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 5",
    id: 160,
    workoutId: 27,
    Workout_Day: "Chest, Triceps, Abs",
    exerciseId: 163,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 161,
    workoutId: 27,
    Workout_Day: "Chest, Triceps, Abs",
    exerciseId: 163,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 5",
    id: 162,
    workoutId: 27,
    Workout_Day: "Chest, Triceps, Abs",
    exerciseId: 163,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 5",
    id: 163,
    workoutId: 28,
    Workout_Day: "Back, Biceps, Abs",
    exerciseId: 913,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 164,
    workoutId: 28,
    Workout_Day: "Back, Biceps, Abs",
    exerciseId: 174,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 165,
    workoutId: 28,
    Workout_Day: "Back, Biceps, Abs",
    exerciseId: 167,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 5",
    id: 166,
    workoutId: 28,
    Workout_Day: "Back, Biceps, Abs",
    exerciseId: 347,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 167,
    workoutId: 28,
    Workout_Day: "Back, Biceps, Abs",
    exerciseId: 347,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 5",
    id: 168,
    workoutId: 28,
    Workout_Day: "Back, Biceps, Abs",
    exerciseId: 1723,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 169,
    workoutId: 28,
    Workout_Day: "Back, Biceps, Abs",
    exerciseId: 2888,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 5",
    id: 170,
    workoutId: 28,
    Workout_Day: "Back, Biceps, Abs",
    exerciseId: 2635,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 171,
    workoutId: 28,
    Workout_Day: "Back, Biceps, Abs",
    exerciseId: 2635,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 5",
    id: 172,
    workoutId: 28,
    Workout_Day: "Back, Biceps, Abs",
    exerciseId: 2635,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 5",
    id: 173,
    workoutId: 29,
    Workout_Day: "Legs, Abs",
    exerciseId: 2192,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 174,
    workoutId: 29,
    Workout_Day: "Legs, Abs",
    exerciseId: 458,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 175,
    workoutId: 29,
    Workout_Day: "Legs, Abs",
    exerciseId: 2530,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 5",
    id: 176,
    workoutId: 29,
    Workout_Day: "Legs, Abs",
    exerciseId: 2232,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 177,
    workoutId: 29,
    Workout_Day: "Legs, Abs",
    exerciseId: 2232,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 5",
    id: 178,
    workoutId: 29,
    Workout_Day: "Legs, Abs",
    exerciseId: 1739,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 179,
    workoutId: 29,
    Workout_Day: "Legs, Abs",
    exerciseId: 1739,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 5",
    id: 180,
    workoutId: 29,
    Workout_Day: "Legs, Abs",
    exerciseId: 104,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 181,
    workoutId: 29,
    Workout_Day: "Legs, Abs",
    exerciseId: 169,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 5",
    id: 182,
    workoutId: 29,
    Workout_Day: "Legs, Abs",
    exerciseId: 2890,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 183,
    workoutId: 29,
    Workout_Day: "Legs, Abs",
    exerciseId: 159,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 5",
    id: 184,
    workoutId: 29,
    Workout_Day: "Legs, Abs",
    exerciseId: 159,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 185,
    workoutId: 30,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 2885,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 5",
    id: 186,
    workoutId: 30,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 176,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 187,
    workoutId: 30,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 176,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 5",
    id: 188,
    workoutId: 30,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 570,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 189,
    workoutId: 30,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 570,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 5",
    id: 190,
    workoutId: 30,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 2245,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 191,
    workoutId: 30,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 2245,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 5",
    id: 192,
    workoutId: 30,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 198,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 193,
    workoutId: 30,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 198,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 5",
    id: 194,
    workoutId: 30,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 1929,
    reps: 1,
    sets: 1,
    tempo: "",
    rests: 0,
  },
  {
    Workout: "SWOLE pt 5",
    id: 195,
    workoutId: 30,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 1929,
    reps: 5,
    sets: 5,
    tempo: "",
    rests: 120,
  },
  {
    Workout: "SWOLE pt 5",
    id: 196,
    workoutId: 30,
    Workout_Day: "Shoulders, Abs",
    exerciseId: 1929,
    reps: 2,
    sets: 2,
    tempo: "",
    rests: 60,
  },
  {
    Workout: "SWOLE pt 5",
    id: 197,
    workoutId: 31,
    Workout_Day: "Cardio, Abs",
    exerciseId: 1632,
    reps: 4,
    sets: 4,
    tempo: "",
    rests: 0,
  },
];
