export interface equipment {
  ID: number;
  Name: string;
  Category: string;
  EquipmentType: string;
  Subcategory: string;
  selected: boolean;
  image?: any;
}

export const equipments: equipment[] = [
  {
    ID: 1,
    selected: false,
    Name: "Dumbbells",
    Category: "Dumbbells",
    EquipmentType: "Free Weights",
    Subcategory: "",
    image: require("../../../../assets/images/equipments/dumbbells.png"),
  },
  {
    ID: 2,
    selected: false,
    Name: "Barbells",
    Category: "Barbells",
    EquipmentType: "Free Weights",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/barbells.png"),
  },
  {
    ID: 3,
    selected: false,
    Name: "Ez Bar",
    Category: "Barbells",
    EquipmentType: "Free Weights",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/ezBar.png"),
  },
  {
    ID: 4,
    selected: false,
    Name: "Trap Bar",
    Category: "Barbells",
    EquipmentType: "Free Weights",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/trapBar.png"),
  },
  {
    ID: 5,
    selected: false,
    Name: "Kettlebells",
    Category: "Kettlebells",
    EquipmentType: "Free Weights",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/kettlebells.png"),
  },
  {
    ID: 6,
    selected: false,
    Name: "Medicine Ball",
    Category: "Medicine Balls",
    EquipmentType: "Free Weights",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/medicineBall.png"),
  },
  {
    ID: 7,
    selected: false,
    Name: "Back Extension Bench",
    Category: "Benches",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/backExtensionBench.png"),
  },
  {
    ID: 8,
    selected: false,
    Name: "Glute Hame Raise Bench",
    Category: "Benches",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/gluteHameRaiseBench.png"),
  },
  {
    ID: 9,
    selected: false,
    Name: "Reverse Hyper Bench",
    Category: "Benches",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/reverseHyperBench.png"),
  },
  {
    ID: 10,
    selected: false,
    Name: "Flat Bench",
    Category: "Benches",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/flatBench.png"),
  },
  {
    ID: 11,
    selected: false,
    Name: "Barbell Flat Bench",
    Category: "Benches",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/barbellFlatBench.png"),
  },
  {
    ID: 12,
    selected: false,
    Name: "Barbell Decline Bench",
    Category: "Benches",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/barbellDeclineBench.png"),
  },
  {
    ID: 13,
    selected: false,
    Name: "Decline Bench",
    Category: "Benches",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/declineBench.png"),
  },
  {
    ID: 14,
    selected: false,
    Name: "Preacher Curl Bench",
    Category: "Benches",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/preacherCurlBench.png"),
  },
  {
    ID: 15,
    selected: false,
    Name: "Leg Raise",
    Category: "Benches",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/legRaise.png"),
  },
  {
    ID: 16,
    selected: false,
    Name: "Incline Bench",
    Category: "Benches",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/inclineBench.png"),
  },
  {
    ID: 17,
    selected: false,
    Name: "Barbell Incline Bench",
    Category: "Benches",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/barbellInclineBench.png"),
  },
  {
    ID: 18,
    selected: false,
    Name: "Dip Bar",
    Category: "Bars And Racks",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/dipBar.png"),
  },
  {
    ID: 19,
    selected: false,
    Name: "Parallette Bars",
    Category: "Bars And Racks",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/paralletteBars.png"),
  },
  {
    ID: 20,
    selected: false,
    Name: "Pull Up Bar",
    Category: "Bars And Racks",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/pullUpBar.png"),
  },
  {
    ID: 21,
    selected: false,
    Name: "Squat Rack",
    Category: "Bars And Racks",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/squatRack.png"),
  },
  {
    ID: 22,
    selected: false,
    Name: "Olympic Tricep Bar",
    Category: "Bars And Racks",
    EquipmentType: "Benches, Bars, And Racks",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/olympicTricepBar.png"),
  },
  {
    ID: 23,
    selected: false,
    Name: "Crossover Cable",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/crossoverCable.png"),
  },
  {
    ID: 24,
    selected: false,
    Name: "Lat Pulldown Cable",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/latPulldownCable.png"),
  },
  {
    ID: 25,
    selected: false,
    Name: "Row Cable",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/rowCable.png"),
  },
  {
    ID: 26,
    selected: false,
    Name: "Hi Lo Pulley Cable",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "",
    image: require(" ../../../../assets/images/equipments/hiLoPulleyCable.png"),
  },
  {
    ID: 27,
    selected: false,
    Name: "Tricep Pressdown Rope",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "Attachments",
    image: require(" ../../../../assets/images/equipments/tricepPressdownRope.png"),
  },
  {
    ID: 28,
    selected: false,
    Name: "Tricep Pressdown Bar",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "Attachments",
    image: require(" ../../../../assets/images/equipments/tricepPressdownBar.png"),
  },
  {
    ID: 29,
    selected: false,
    Name: "V-Bar Revolving",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "Attachments",
    image: require(" ../../../../assets/images/equipments/vBarRevolving.png"),
  },
  {
    ID: 30,
    selected: false,
    Name: "V-Bar Ergo Grip",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "Attachments",
    image: require(" ../../../../assets/images/equipments/vBarErgoGrip.png"),
  },
  {
    ID: 31,
    selected: false,
    Name: "Multi Purpose Bar",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "Attachments",
    image: require(" ../../../../assets/images/equipments/multiPurposeBar.png"),
  },
  {
    ID: 32,
    selected: false,
    Name: "D Grip",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "Attachments",
    image: require(" ../../../../assets/images/equipments/dGrip.png"),
  },
  {
    ID: 33,
    selected: false,
    Name: "Straight Bar",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "Attachments",
    image: require(" ../../../../assets/images/equipments/straightBar.png"),
  },
  {
    ID: 34,
    selected: false,
    Name: "Lat Bar",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "Attachments",
    image: require(" ../../../../assets/images/equipments/latBar.png"),
  },
  {
    ID: 35,
    selected: false,
    Name: "Seated Row / Chin Bar",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "Attachments",
    image: require(" ../../../../assets/images/equipments/seatedRowChinBar.png"),
  },
  {
    ID: 36,
    selected: false,
    Name: "Curl Bar",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "Attachments",
    image: require(" ../../../../assets/images/equipments/curlBar.png"),
  },
  {
    ID: 37,
    selected: false,
    Name: "Ankle Cuff",
    Category: "Cable Machines",
    EquipmentType: "Machines",
    Subcategory: "Attachments",
    image: require(" ../../../../assets/images/equipments/ankleCuff.png"),
  },
  {
    ID: 38,
    selected: false,
    Name: "Fly Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Misc",
    image: require(" ../../../../assets/images/equipments/flyMachine.png"),
  },
  {
    ID: 39,
    selected: false,
    Name: "Hammer Strength Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Misc",
    image: require(" ../../../../assets/images/equipments/hammerStrengthMachine.png"),
  },
  {
    ID: 40,
    selected: false,
    Name: "Ab Crunch Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Misc",
    image: require(" ../../../../assets/images/equipments/abCrunchMachine.png"),
  },
  {
    ID: 41,
    selected: false,
    Name: "Freemotin Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Misc",
    image: require(" ../../../../assets/images/equipments/freemotinMachine.png"),
  },
  {
    ID: 42,
    selected: false,
    Name: "Smith Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Misc",
    image: require(" ../../../../assets/images/equipments/smithMachine.png"),
  },
  {
    ID: 43,
    selected: false,
    Name: "Assisted Weight Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Misc",
    image: require(" ../../../../assets/images/equipments/assistedWeightMachine.png"),
  },
  {
    ID: 44,
    selected: false,
    Name: "Bicep Curl Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Back And Biceps",
    image: require(" ../../../../assets/images/equipments/bicepCurlMachine.png"),
  },
  {
    ID: 45,
    selected: false,
    Name: "Row Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Back And Biceps",
    image: require(" ../../../../assets/images/equipments/rowMachine.png"),
  },
  {
    ID: 46,
    selected: false,
    Name: "Back Extension Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Back And Biceps",
    image: require(" ../../../../assets/images/equipments/backExtensionMachine.png"),
  },
  {
    ID: 47,
    selected: false,
    Name: "Preacher Curl Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Back And Biceps",
    image: require(" ../../../../assets/images/equipments/preacherCurlMachine.png"),
  },
  {
    ID: 48,
    selected: false,
    Name: "T Bar",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Back And Biceps",
    image: require(" ../../../../assets/images/equipments/tBar.png"),
  },
  {
    ID: 49,
    selected: false,
    Name: "Bench Press Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Chest, Shoulders, And Triceps",
    image: require(" ../../../../assets/images/equipments/benchPressMachine.png"),
  },
  {
    ID: 50,
    selected: false,
    Name: "Shoulder Shrug Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Chest, Shoulders, And Triceps",
    image: require(" ../../../../assets/images/equipments/shoulderShrugMachine.png"),
  },
  {
    ID: 51,
    selected: false,
    Name: "Shoulder Press Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Chest, Shoulders, And Triceps",
    image: require(" ../../../../assets/images/equipments/shoulderPressMachine.png"),
  },
  {
    ID: 52,
    selected: false,
    Name: "Tricep Dip Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Chest, Shoulders, And Triceps",
    image: require(" ../../../../assets/images/equipments/tricepDipMachine.png"),
  },
  {
    ID: 53,
    selected: false,
    Name: "Calf Raise Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Legs",
    image: require(" ../../../../assets/images/equipments/calfRaiseMachine.png"),
  },
  {
    ID: 54,
    selected: false,
    Name: "Leg Curl Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Legs",
    image: require(" ../../../../assets/images/equipments/legCurlMachine.png"),
  },
  {
    ID: 55,
    selected: false,
    Name: "Leg Press",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Legs",
    image: require(" ../../../../assets/images/equipments/legPress.png"),
  },
  {
    ID: 56,
    selected: false,
    Name: "Hack Squat Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Legs",
    image: require(" ../../../../assets/images/equipments/hackSquatMachine.png"),
  },
  {
    ID: 57,
    selected: false,
    Name: "Leg Extension Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Legs",
    image: require(" ../../../../assets/images/equipments/legExtensionMachine.png"),
  },
  {
    ID: 58,
    selected: false,
    Name: "Squat Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Legs",
    image: require(" ../../../../assets/images/equipments/squatMachine.png"),
  },
  {
    ID: 59,
    selected: false,
    Name: "Thigh Abductor Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Legs",
    image: require(" ../../../../assets/images/equipments/thighAbductorMachine.png"),
  },
  {
    ID: 60,
    selected: false,
    Name: "Thigh Adductor Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Legs",
    image: require(" ../../../../assets/images/equipments/thighAdductorMachine.png"),
  },
  {
    ID: 61,
    selected: false,
    Name: "Tricep Extension Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Legs",
    image: require(" ../../../../assets/images/equipments/tricepExtensionMachine.png"),
  },
  {
    ID: 62,
    selected: false,
    Name: "Leg Press Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Legs",
    image: require(" ../../../../assets/images/equipments/legPressMachine.png"),
  },
  {
    ID: 63,
    selected: false,
    Name: "Glute Kickback Machine",
    Category: "Weight Machines",
    EquipmentType: "Machines",
    Subcategory: "Legs",
    image: require(" ../../../../assets/images/equipments/gluteKickbackMachine.png"),
  },
  {
    ID: 64,
    selected: false,
    Name: "Mini Loop Bands",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Mini Loop Bands",
    image: require(" ../../../../assets/images/equipments/miniLoopBands.png"),
  },
  {
    ID: 65,
    selected: false,
    Name: "Handle Bands",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/handleBands.png"),
  },
  {
    ID: 66,
    selected: false,
    Name: "Power Loop Bands",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/powerLoopBands.png"),
  },
  {
    ID: 67,
    selected: false,
    Name: "Box",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/box.png"),
  },
  {
    ID: 68,
    selected: false,
    Name: "Farmers Walk Handles",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/farmersWalkHandles.png"),
  },
  {
    ID: 69,
    selected: false,
    Name: "Stability Ball",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/stabilityBall.png"),
  },
  {
    ID: 70,
    selected: false,
    Name: "Trx",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/trx.png"),
  },
  {
    ID: 71,
    selected: false,
    Name: "Bosu Ball",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/bosuBall.png"),
  },
  {
    ID: 72,
    selected: false,
    Name: "Foam Roller",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/foamRoller.png"),
  },
  {
    ID: 73,
    selected: false,
    Name: "Pvc Pipe",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/pvcPipe.png"),
  },
  {
    ID: 74,
    selected: false,
    Name: "Cone",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/cone.png"),
  },
  {
    ID: 75,
    selected: false,
    Name: "Rings",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/rings.png"),
  },
  //   {
  //     ID: 76,
  //     selected: false,Name: "Sled",
  //     Category: "Bands",
  //     EquipmentType: "Bands And More",
  //     Subcategory: "Other",
  //     image: require(" ../../../../assets/images/equipments/sled.png"),
  //   },
  //   {
  //     ID: 77,
  //     selected: false,Name: "Tire",
  //     Category: "Bands",
  //     EquipmentType: "Bands And More",
  //     Subcategory: "Other",
  //     image: require(" ../../../../assets/images/equipments/tire.png"),
  //   },
  {
    ID: 78,
    selected: false,
    Name: "Yoke",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/yoke.png"),
  },
  {
    ID: 79,
    selected: false,
    Name: "Battle Ropes",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/battleRopes.png"),
  },
  {
    ID: 80,
    selected: false,
    Name: "Ab Wheel",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/abWheel.png"),
  },
  {
    ID: 81,
    selected: false,
    Name: "Landmine",
    Category: "Bands",
    EquipmentType: "Bands And More",
    Subcategory: "Other",
    image: require(" ../../../../assets/images/equipments/landmine.png"),
  },
  {
    ID: 82,
    selected: false,
    Name: "Mat",
    Category: "Other",
    EquipmentType: "Other",
    Subcategory: "Other",
  },
];
