export const TEST = {
    SET_TEXT: 'SET_TEXT',
};

export const WORKOUT_PREVIEW = {
    SET_PREVIEW: 'WORKOUT_PREVIEW/SET_PREVIEW',
    ADD_EXERCISE_ID: 'WORKOUT_PREVIEW/ADD_EXERCISE_ID',
    // hossein added after exercise detail id
    ADD_EXERCISE_DETAIL_ID: 'WORKOUT_PREVIEW/ADD_EXERCISE_DETAIL_ID',
}

export const WORKOUT_PLAN_PROG = {
    START: 'WORKOUT_PLAN_PROG/START',
    STOP: 'WORKOUT_PLAN_PROG/STOP',
    SET_NOTES: 'WORKOUT_PLAN_PROG/SET_NOTES',
    UPDATE: 'WORKOUT_PLAN_PROG/UPDATE',
};

export const WORKOUT_PROG = {
    UPDATE: 'WORKOUT_PROG/UPDATE',
    START: 'WORKOUT_PROG/START',
    STOP: 'WORKOUT_PROG/STOP',
    SET_NOTES: 'WORKOUT_PROG/SET_NOTES',
    ADD_EXERCISE_HISTORY: 'WORKOUT_PROG/ADD_EXERCISE_HISTORY',
};

export const EXERCISE_PROG = {
    UPDATE: 'EXERCISE_PROG/UPDATE',
    START: 'EXERCISE_PROG/START',
    STOP: 'EXERCISE_PROG/STOP',
    SET_NOTES: 'EXERCISE_PROG/SET_NOTES',
}

export const SET_PROG = {
    START: 'SET_PROG/START',
    STOP: 'SET_PROG/STOP',
    SET_NOTES: 'SET_PROG/SET_NOTES',
    UPDATE: 'SET_PROG/UPDATE',
}


export const CREATING_WORKOUT = {
    ADD_EXERCISE: 'CREATING_WORKOUT/ADD_EXERCISE',
    UPDATE_EXERCISE: 'CREATING_WORKOUT/UPDATE_EXERCISE',
    INSERT_EXERCISE: 'CREATING_WORKOUT/INSERT_EXERCISE',
    REMOVE_EXERCISE: 'CREATING_WORKOUT/REMOVE_EXERCISE',
    CLEAR_EXERCISES: 'CREATING_WORKOUT/CLEAR_EXERCISES',
    SET_EXERCISES: 'CREATING_WORKOUT/SET_EXERCISES',
    SET_NAME: 'CREATING_WORKOUT/SET_NAME',
    SET_NOTES: 'CREATING_WORKOUT/SET_NOTES',
    SET_ID: 'CREATING_WORKOUT/SET_ID',
    // Exercise Details 2/12/2021
    // INSERT_EXERCISE_NAME: 'CREATING_WORKOUT/INSERT_NAME',
    INSERT_NUMBER_OF_SETS: 'CREATING_WORKOUT/INSERT_NUMBER_OF_SETS',
    INSERT_NUMBER_OF_REPS: 'CREATING_WORKOUT/INSERT_NUMBER_OF_REPS',
    INSERT_TEMPO: 'CREATING_WORKOUT/INSERT_TEMPO',
    INSERT_REST_DURATION: 'CREATING_WORKOUT/INSERT_REST_DURATION',
};

export const CREATING_WORKOUT_PLAN = {
    ADD_WORKOUT: 'CREATING_WORKOUT_PLAN/ADD_WORKOUT',
    UPDATE_WORKOUT: 'CREATING_WORKOUT_PLAN/UPDATE_WORKOUT',
    INSERT_WORKOUT: 'CREATING_WORKOUT_PLAN/INSERT_WORKOUT',
    REMOVE_WORKOUT: 'CREATING_WORKOUT_PLAN/REMOVE_WORKOUT',
    CLEAR_WORKOUTS: 'CREATING_WORKOUT_PLAN/CLEAR_WORKOUTS',
    SET_WORKOUTS: 'CREATING_WORKOUT_PLAN/SET_WORKOUTS',
    SET_NAME: 'CREATING_WORKOUT_PLAN/SET_NAME',
    SET_NOTES: 'CREATING_WORKOUT_PLAN/SET_NOTES',
    SET_ID: 'CREATING_WORKOUT_PLAN/SET_ID',
};

export const CREATING_EXERCISE = {
    SET_ID: 'CREATING_EXERCISE/SET_ID',
    SET_NAME: 'CREATING_EXERCISE/SET_NAME',
    SET_SETS: 'CREATING_EXERCISE/SET_SETS',
    SET_REPS: 'CREATING_EXERCISE/SET_REPS',
    SET_RESTS: 'CREATING_EXERCISE/SET_RESTS',
    SET_DESCRIPTION: 'CREATING_EXERCISE/SET_DESCRIPTION',
    SET_SUPERSET_ID: 'CREATE_CREATING_EXERCISE_SUPERSET_ID'
};

export const CREATING_CARDIO = {
    SET_ID: 'CREATING_CARDIO/SET_ID',
    SET_NAME: 'CREATING_CARDIO/SET_NAME',
    SET_DESCRIPTION: 'CREATING_CARDIO/SET_DESCRIPTION',
};

export const CREATING_EQUIPMENT = {
    SET_ID: 'CREATING_EQUIPMENT/SET_ID',
    SET_NAME: 'CREATING_EQUIPMENT/SET_NAME',
    SET_TYPE: 'CREATING_EQUIPMENT/SET_TYPE',
};

export const TIMER = {
    SAVE_TIMER: 'TIMER/SAVE_TIMER',
    SAVE_ACTIVE: 'TIMER/SAVE_ACTIVE',
    SAVE_PAUSED: 'TIMER/SAVE_PAUSED',
    SAVE_UPDATED: 'TIMER/SAVE_UPDATED',
    SAVE_NUM_SETS: 'TIMER/SAVE_NUM_SETS',
    SAVE_CURRENT_SET: 'TIMER/SAVE_CURRENT_SET',
    SAVE_MINUTES_INPUT: 'TIMER/SAVE_MINUTES_INPUT',
    SAVE_SECONDS_INPUT: 'TIMER/SAVE_SECONDS_INPUT',
    SAVE_REST_MINUTES_INPUT: 'TIMER/SAVE_REST_MINUTES_INPUT',
    SAVE_REST_SECONDS_INPUT: 'TIMER/SAVE_REST_SECONDS_INPUT',

    INPUTS_VIEW: 'TIMER/INPUTS_VIEW',
    COUNTDOWN_VIEW: 'TIMER/COUNTDOWN_VIEW',
    SAVE_VIEW: 'TIMER/SAVE_VIEW',
    
    // this is for rest period count down timer
    START_REST_TIMER: 'START_REST_TIMER',
    TICK_REST_TIMER: 'TICK_REST_TIMER',
    STOP_REST_TIMER: 'STOP_REST_TIMER',
    SET_REST_TIMER: 'SET_REST_TIMER'
};

export const SETS_REPS = {
    UPDATE_SET: 'SETS_REPS/UPDATE_SET',
    ADD_SET: 'SETS_REPS/ADD_SET',
    REMOVE_SET: 'SETS_REPS/REMOVE_SET',
    SET_CURRENT_INDEX: 'SETS_REPS/SET_CURRENT_INDEX',
    SET_CURRENT_WEIGHT: 'SETS_REPS/CURRENT_WEIGHT',
    SET_CURRENT_REPS: 'SETS_REPS/CURRENT_REPS',


    SET_CURRENT_NOTE: 'SETS_REPS/CURRENT_NOTE',
    SET_CURRENT_TEMPO: 'SETS_REPS/CURRENT_TEMPO',
    SET_CURRENT_INJURY: 'SETS_REPS/CURRENT_INJURY',

    // multi tempo input
    CURRENT_TEMPO_ONE: 'SETS_REPS/CURRENT_TEMPO_ONE',
    CURRENT_TEMPO_TWO: 'SETS_REPS/CURRENT_TEMPO_TWO',
    CURRENT_TEMPO_THREE: 'SETS_REPS/CURRENT_TEMPO_THREE',
    CURRENT_TEMPO_FOUR: 'SETS_REPS/CURRENT_TEMPO_FOUR',


};

export const WORKOUT_PLAN = {
    REQUESTING: 'WORKOUT_PLAN/REQUESTING',
    RECEIVED: 'WORKOUT_PLAN/RECEIVED',
    ADD_WORKOUT_PLAN: 'WORKOUT_PLAN/ADD_WORKOUT_PLAN',
    REMOVE_WORKOUT_PLAN: 'WORKOUT_PLAN/REMOVE_WORKOUT_PLAN',
    ADD_WORKOUT: 'WORKOUT_PLAN/ADD_DAY',
    REMOVE_WORKOUT: 'WORKOUT_PLAN/REMOVE_DAY',
    COMPLETE_WORKOUT: 'WORKOUT_PLAN/COMPLETE_DAY',
    UPDATE_WORKOUT_PLAN: 'WORKOUT_PLAN/UPDATE_WORKOUT_PLAN',
    SET_CURRENT_WORKOUT_PLAN: 'WORKOUT_PAN/SET_CURRENT_WORKOUT_PLAN',
};

export const WORKOUT = {
    REQUESTING: 'WORKOUT/REQUESTING',
    RECEIVED: 'WORKOUT/RECEIVED',
    ADD_WORKOUT: 'WORKOUT/ADD_WORKOUT',
    REMOVE_WORKOUT: 'WORKOUT/REMOVE_WORKOUT',
    COMPLETE_EXERCISE: 'WORKOUT/COMPLETE_EXERCISE',
    UPDATE_WORKOUT: 'WORKOUT/UPDATE_WORKOUT',

    //hossein importing workout json files----test
    
};

export const EXERCISE = {
    REQUESTING: 'EXERCISE/REQUESTING',
    RECEIVED: 'EXERCISE/RECEIVED',
    ADD_EXERCISE: 'EXERCISE/ADD_EXERCISE',
    ADD_EXERCISES: 'EXERCISE/ADD_EXERCISES',
    REMOVE_EXERCISE: 'EXERCISE/REMOVE_EXERCISE',
    UPDATE_EXERCISE: 'EXERCISE/UPDATE_EXERCISE',

};

export const EXERCISE_DETAILS = {
    SET_ID: 'EXERCISE_DETAILS/SET_ID',
    NUMBER_OF_SETS: 'EXERCISE_DETAILS/NUMBER_OF_SETS',
    NUMBER_OF_REPS: 'EXERCISE_DETAILS/NUMBER_OF_REPS',
    REST_DURATION: 'EXERCISE_DETAILS/REST_DURATION',
    EXERCISE_TEMPO: 'EXERCISE_DETAILS/EXERCISE_TEMPO',
    ADD_EXERCISE_DETAIL: 'EXERCISE_DETAILS/ADD_EXERCISE_DETAIL',
    ADD_WORKOUTID_TO_DETAIL: 'EXERCISE_DETAILS/ADD_WORKOUTID_TO_DETAIL',
    UPDATE_EXERCISE_DETAIL: 'EXERCISE_DETAILS/UPDATE_EXERCISE_DETAIL'
    // UPDATING 
    // UPDATE_EXERCISE: 'CREATING_WORKOUT/UPDATE_EXERCISE',
    // INSERT_EXERCISE: 'CREATING_WORKOUT/INSERT_EXERCISE',
    // REMOVE_EXERCISE: 'CREATING_WORKOUT/REMOVE_EXERCISE',
    // CLEAR_EXERCISES: 'CREATING_WORKOUT/CLEAR_EXERCISES',
};

export const CARDIO = {
    REQUESTING: 'CARDIO/REQUESTING',
    RECEIVED: 'CARDIO/RECEIVED',
    ADD_CARDIO: 'CARDIO/ADD_CARDIO',
    REMOVE_CARDIO: 'CARDIO/REMOVE_CARDIO',
};

export const EQUIPMENT = {
    REQUESTING: 'EQUIPMENT/REQUESTING',
    RECEIVED: 'EQUIPMENT/RECEIVED',
    ADD_EQUIPMENT: 'EQUIPMENT/ADD_EQUIPMENT',
    REMOVE_EQUIPMENT: 'EQUIPMENT/REMOVE_EQUIPMENT'
};

export const WEIGHT_REPS_INPUT = {
    WEIGHT_INPUT: 'WEIGHT_REPS_INPUT/WEIGHT_INPUT',
    REPS_INPUT: 'WEIGHT_REPS_INPUT/REPS_INPUT',
    NOTE_INPUT: 'WEIGHT_REPS_INPUT/NOTE_INPUT',
    TEMPO_INPUT: 'WEIGHT_REPS_INPUT/TEMPO_INPUT',
    INJURY_INPUT: 'WEIGHT_REPS_INPUT/INJURY_INPUT',

    INPUT: 'TIMER/INPUTS_VIEW',

};

export const CARDIO_LOG = {
    SAVE_LEVEL: 'CARDIO_LOG/LEVEL',
    SAVE_SPEED: 'CARDIO_LOG/SPEED',
    SAVE_MINUTES: 'CARDIO_LOG/SAVE_MINUTES',
    CARDIO_SAVE_LOG_ENTERY: 'CARDIO_LOG/CARDIO_SAVE_LOG_ENTERY',
    CARDIO_REMOVE_LOG_ENTERY: 'CARDIO_LOG/CARDIO_REMOVE_LOG_ENTERY',
};

export const SETS_AND_REPS_ENTRY = {
    SAVE_WEIGHT: 'SETS_AND_REPS_ENTRY/SAVE_WEIGHT',
    SAVE_REPS: 'SETS_AND_REPS_ENTRY/SAVE_REPS',
    SAVE_NOTE: 'SETS_AND_REPS_ENTRY/SAVE_NOTE',
    SAVE_TEMPO: 'SETS_AND_REPS_ENTRY/SAVE_TEMPO',
    SETS_AND_REPS_SAVE_LOG_ENTRY: 'SETS_AND_REPS_ENTRY/SETS_AND_REPS_SAVE_LOG_ENTRY',
    SETS_AND_REPS_REMOVE_LOG_ENTRY: 'SETS_AND_REPS_ENTRY/SETS_AND_REPS_REMOVE_LOG_ENTRY',
};

export const SET_HISTORY = {
    ADD: 'SET_HISTORY/ADD',
    UPDATE: 'SET_HISTORY/UPDATE',
    REMOVE: 'SET_HISTORY/REMOVE',
};

export const EXERCISE_HISTORY = {
    ADD: 'EXERCISE_HISTORY/ADD',
    UPDATE: 'EXERCISE_HISTORY/UPDATE',
    REMOVE: 'EXERCISE_HISTORY/REMOVE',
};

export const WORKOUT_HISTORY = {
    ADD: 'WORKOUT_HISTORY/ADD',
    UPDATE: 'WORKOUT_HISTORY/UPDATE',
    REMOVE: 'WORKOUT_HISTORY/REMOVE',
};

export const WORKOUT_PLAN_HISTORY = {
    ADD: 'WORKOUT_PLAN_HISTORY/ADD',
    UPDATE: 'WORKOUT_PLAN_HISTORY/UPDATE',
    REMOVE: 'WORKOUT_PLAN_HISTORY/REMOVE',
};

export const EQUIPMENTS = {
    SELECT: 'SELECT_EQUIPMENTS',
    DESELECT: 'DESELECT_EQUIPMENT'
}